-- Muheeb notification RPC fix
-- Run once in Supabase SQL Editor if assigned-note notifications still fail.

create table if not exists public.admin_notifications (
    id bigint generated by default as identity primary key,
    actor_user_id uuid,
    target_user_id uuid,
    lead_id bigint,
    note_id text,
    kind text not null default 'note_done',
    title text not null,
    message text not null,
    read_by uuid[] not null default '{}',
    created_at timestamptz not null default now()
);

alter table public.admin_notifications
    add column if not exists actor_user_id uuid,
    add column if not exists target_user_id uuid,
    add column if not exists lead_id bigint,
    add column if not exists note_id text,
    add column if not exists kind text default 'note_done',
    add column if not exists title text,
    add column if not exists message text,
    add column if not exists read_by uuid[] default '{}',
    add column if not exists created_at timestamptz default now();

do $$
declare
    item record;
begin
    for item in
        select distinct c.conname
        from pg_constraint c
        join pg_attribute a on a.attrelid = c.conrelid and a.attnum = any(c.conkey)
        where c.conrelid = 'public.admin_notifications'::regclass
        and c.contype = 'f'
        and a.attname in ('actor_user_id', 'target_user_id', 'lead_id')
    loop
        execute format('alter table public.admin_notifications drop constraint if exists %I', item.conname);
    end loop;
end $$;

update public.admin_notifications
set kind = coalesce(kind, 'note_done'),
    title = coalesce(title, 'إشعار'),
    message = coalesce(message, ''),
    read_by = coalesce(read_by, '{}'),
    created_at = coalesce(created_at, now());

alter table public.admin_notifications
    alter column kind set not null,
    alter column kind set default 'note_done',
    alter column title set not null,
    alter column message set not null,
    alter column read_by set not null,
    alter column read_by set default '{}',
    alter column created_at set not null,
    alter column created_at set default now();

alter table public.admin_notifications enable row level security;

grant select, insert, update on table public.admin_notifications to authenticated;

do $$
begin
    if exists (
        select 1
        from pg_class c
        join pg_namespace n on n.oid = c.relnamespace
        where n.nspname = 'public'
        and c.relname = 'admin_notifications_id_seq'
        and c.relkind = 'S'
    ) then
        grant usage, select on sequence public.admin_notifications_id_seq to authenticated;
    end if;
end $$;

drop policy if exists "Admins can read notifications" on public.admin_notifications;
create policy "Admins can read notifications"
on public.admin_notifications
for select
to authenticated
using (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
);

drop policy if exists "Admins can create notifications" on public.admin_notifications;
create policy "Admins can create notifications"
on public.admin_notifications
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update notification reads" on public.admin_notifications;
create policy "Admins can update notification reads"
on public.admin_notifications
for update
to authenticated
using (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
)
with check (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
);

create or replace function public.create_admin_notification(
    p_target_user_id uuid,
    p_lead_id bigint,
    p_note_id text,
    p_kind text,
    p_title text,
    p_message text
)
returns public.admin_notifications
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted_notification public.admin_notifications;
begin
    if not public.is_admin() then
        raise exception 'هذا الحساب ليس لديه صلاحية إنشاء إشعار.' using errcode = '42501';
    end if;

    insert into public.admin_notifications (
        actor_user_id,
        target_user_id,
        lead_id,
        note_id,
        kind,
        title,
        message
    )
    values (
        auth.uid(),
        p_target_user_id,
        p_lead_id,
        nullif(p_note_id, ''),
        coalesce(nullif(p_kind, ''), 'note_done'),
        coalesce(nullif(p_title, ''), 'إشعار'),
        coalesce(p_message, '')
    )
    returning * into inserted_notification;

    return inserted_notification;
end;
$$;

grant execute on function public.create_admin_notification(uuid, bigint, text, text, text, text) to authenticated;
