-- Muheeb precision admin cleanup
-- Run once after the latest admin update.

create table if not exists public.admin_notifications (
    id bigint generated by default as identity primary key,
    actor_user_id uuid references auth.users(id) on delete set null,
    target_user_id uuid references auth.users(id) on delete cascade,
    lead_id bigint references public.leads(id) on delete cascade,
    note_id text,
    kind text not null default 'note_done',
    title text not null,
    message text not null,
    read_by uuid[] not null default '{}',
    created_at timestamptz not null default now()
);

alter table public.admin_notifications
    add column if not exists actor_user_id uuid references auth.users(id) on delete set null,
    add column if not exists target_user_id uuid references auth.users(id) on delete cascade,
    add column if not exists lead_id bigint references public.leads(id) on delete cascade,
    add column if not exists note_id text,
    add column if not exists kind text default 'note_done',
    add column if not exists title text,
    add column if not exists message text,
    add column if not exists read_by uuid[] default '{}',
    add column if not exists created_at timestamptz default now();

update public.admin_notifications
set kind = coalesce(kind, 'note_done'),
    title = coalesce(title, 'إشعار'),
    message = coalesce(message, ''),
    read_by = coalesce(read_by, '{}'),
    created_at = coalesce(created_at, now());

alter table public.admin_notifications
    alter column kind set not null,
    alter column kind set default 'note_done',
    alter column title set not null,
    alter column message set not null,
    alter column read_by set not null,
    alter column read_by set default '{}',
    alter column created_at set not null,
    alter column created_at set default now();

alter table public.admin_notifications enable row level security;

create index if not exists admin_notifications_target_user_id_idx
on public.admin_notifications (target_user_id);

create index if not exists admin_notifications_created_at_idx
on public.admin_notifications (created_at desc);

update public.site_images
set published = false,
    updated_at = now()
where image_key = 'footer_main_image';

insert into public.site_content
    (content_key, label, value, input_type, group_name, sort_order)
values
    ('event_about_eyebrow', 'عنوان صغير لقسم عن الفعالية', 'عن الفعالية', 'text', 'صفحة الفعالية', 170),
    ('event_highlights_eyebrow', 'عنوان صغير للنقاط المختصرة', 'نقاط مختصرة للعرض', 'text', 'صفحة الفعالية', 171),
    ('event_highlights_title', 'عنوان النقاط المختصرة', 'ملخص سريع لما يميز الفعالية', 'text', 'صفحة الفعالية', 172),
    ('event_achievements_eyebrow', 'عنوان صغير للإنجازات', 'الإنجازات المحققة', 'text', 'صفحة الفعالية', 173),
    ('event_achievements_title', 'عنوان الإنجازات', 'نتائج ومخرجات الفعالية', 'text', 'صفحة الفعالية', 174),
    ('event_gallery_eyebrow', 'عنوان صغير لمعرض صور الفعالية', 'معرض الصور', 'text', 'صفحة الفعالية', 175),
    ('event_gallery_title', 'عنوان معرض صور الفعالية', 'مشاهد من الفعالية', 'text', 'صفحة الفعالية', 176),
    ('event_partners_eyebrow', 'عنوان صغير للجهات المشاركة', 'الجهات والشركاء', 'text', 'صفحة الفعالية', 177),
    ('event_partners_title', 'عنوان الجهات المشاركة', 'الجهات المشاركة أو الداعمة', 'text', 'صفحة الفعالية', 178),
    ('event_sections_eyebrow', 'عنوان صغير لأقسام الفعالية', 'تفاصيل إضافية', 'text', 'صفحة الفعالية', 179),
    ('event_sections_title', 'عنوان أقسام الفعالية', 'كل ما يتعلق بالفعالية', 'text', 'صفحة الفعالية', 180)
on conflict (content_key) do update
set label = excluded.label,
    input_type = excluded.input_type,
    group_name = excluded.group_name,
    sort_order = excluded.sort_order;

drop policy if exists "Admins can read notifications" on public.admin_notifications;
create policy "Admins can read notifications"
on public.admin_notifications
for select
using (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
);

drop policy if exists "Admins can create notifications" on public.admin_notifications;
create policy "Admins can create notifications"
on public.admin_notifications
for insert
with check (public.is_admin());

drop policy if exists "Admins can update notification reads" on public.admin_notifications;
create policy "Admins can update notification reads"
on public.admin_notifications
for update
using (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
)
with check (
    public.is_admin()
    and (
        target_user_id is null
        or target_user_id = auth.uid()
    )
);
